### ISSUE TITLE
App crashes on run

### ISSUE THREAD

**Issue by danirabbit** [SuburbanFilth/Noted#15]
Installed noted from packaging but then:
```
Failed to import module main.py to launch noted!
ERROR: No module named logger
Installation was assumed to be at: /usr/share/com.github.suburbanfilth.noted/noted
```

**Comment by mirkobrombin** [comment]
@SuburbanFilth I think you need to create a setup.py that run from the postinst of the debian package.

debian/**postinst**
```
#!/bin/sh

set -e

cd /usr/share/com.github.suburbanfilth.noted
sudo python setup.py install
```
I think your path is not the one I've indicated
**setup.py** like [this](https://github.com/mirkobrombin/Football/blob/master/setup.py)

Consequently, take a look at the structure of other [files](https://github.com/mirkobrombin/Football/tree/master/debian).

**Comment by marsp0** [comment]
@mirkobrombin thank you for the help! I will check it out as soon as I can.

**Comment by marsp0** [comment]
I fixed the issue by just adding the logger folder to the packages list in the setup.py file. If there are anymore issues, I will try to follow the structure that @mirkobrombin pointed out.

**Comment by danirabbit** [comment]
New error message:

```
Traceback (most recent call last):
  File "/usr/bin/com.github.suburbanfilth.noted", line 24, in <module>
    main.start()
  File "/usr/share/com.github.suburbanfilth.noted/noted/main.py", line 268, in start
    win = MainWindow()
  File "/usr/share/com.github.suburbanfilth.noted/noted/main.py", line 60, in __init__
    self.start_database()
  File "/usr/share/com.github.suburbanfilth.noted/noted/logger/logger.py", line 26, in wrapper
    raise e
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: note.deleted_notebook_name [SQL: u'SELECT note.idd AS note_idd, note.name AS note_name, note.content AS note_content, note.notebook_id AS note_notebook_id, note.deleted_notebook_name AS note_deleted_notebook_name, note.deleted_notebook_id AS note_deleted_notebook_id \nFROM note \nWHERE note.notebook_id = ?'] [parameters: (1,)]
```
